import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import SplashCursor from "@/components/Splash";
import CursorLayer from "@/components/CursorLayer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kaalnetra",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/Pictures/Favicon.png", type: "image/png", sizes: "any" },
    ],
    apple: [
      { url: "/Pictures/Favicon.png", type: "image/png", sizes: "any" },
    ],
    shortcut: ["/Pictures/Favicon.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SplashCursor TRANSPARENT BACK_COLOR={{ r: 0, g: 0, b: 0 }} />
        <CursorLayer />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
